#!/bin/bash
# list-recent-sessions.sh — dispatcher for recent-sessions skill.
#
# Modular architecture:
#   - Reads config from <skill>/config.env (generated by setup.sh).
#   - Sources <skill>/scripts/sources/_common.sh for shared helpers.
#   - Sources each enabled <skill>/scripts/sources/<name>.sh.
#   - Dispatches scan_<name>() for every enabled source.
#
# TSV output: mtime_epoch\tmtime_iso\tsource\tproject\tidentifier\thint
# (Or JSON lines with --json.)

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SOURCES_DIR="$SCRIPT_DIR/sources"
CONFIG_FILE="$SKILL_DIR/config.env"

HOURS=72
LIMIT=30
JSON=0
OVERRIDE_SOURCES=()
RUN_SETUP=0

usage() {
  cat <<USAGE
Usage: $(basename "$0") [options]

  --hours N        Look back N hours (default 72)
  --limit N        Cap to N rows total (default 30)
  --source NAME    Restrict to one source (repeat for more).
                   Overrides config.env. Names: claude codex gemini cursor
                   vscode volumes anthropic
  --json           Emit JSON lines rather than TSV
  --setup          Run the interactive setup and exit
  -h, --help       This help

Configuration lives in: $CONFIG_FILE
(Run --setup to (re)create it.)
USAGE
}

while (($#)); do
  case "$1" in
    --hours)  HOURS="$2"; shift 2 ;;
    --limit)  LIMIT="$2"; shift 2 ;;
    --source) OVERRIDE_SOURCES+=("$2"); shift 2 ;;
    --json)   JSON=1; shift ;;
    --setup)  RUN_SETUP=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown arg: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ "$RUN_SETUP" -eq 1 ]]; then
  exec bash "$SCRIPT_DIR/setup.sh"
fi

# Defaults (used when no config.env exists yet).
SOURCE_CLAUDE=1
SOURCE_CODEX=1
SOURCE_GEMINI=1
SOURCE_CURSOR=1
SOURCE_VSCODE=1
SOURCE_VOLUMES=0
SOURCE_ANTHROPIC=0
ANTHROPIC_SECRETS_FILE=""

# Load config if present. Must be after defaults so config overrides, and
# before --source overrides so CLI wins over file.
if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
fi

# --source on the CLI replaces the config-driven enable map entirely.
if [[ ${#OVERRIDE_SOURCES[@]} -gt 0 ]]; then
  SOURCE_CLAUDE=0 SOURCE_CODEX=0 SOURCE_GEMINI=0
  SOURCE_CURSOR=0 SOURCE_VSCODE=0 SOURCE_VOLUMES=0 SOURCE_ANTHROPIC=0
  for s in "${OVERRIDE_SOURCES[@]}"; do
    case "$s" in
      claude)    SOURCE_CLAUDE=1 ;;
      codex)     SOURCE_CODEX=1 ;;
      gemini)    SOURCE_GEMINI=1 ;;
      cursor)    SOURCE_CURSOR=1 ;;
      vscode)    SOURCE_VSCODE=1 ;;
      volumes)   SOURCE_VOLUMES=1 ;;
      anthropic) SOURCE_ANTHROPIC=1 ;;
      *) echo "unknown --source: $s" >&2; exit 2 ;;
    esac
  done
fi

# Anthropic secret: source an env file if one was configured.
if [[ "$SOURCE_ANTHROPIC" -eq 1 && -n "${ANTHROPIC_SECRETS_FILE:-}" && -f "$ANTHROPIC_SECRETS_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ANTHROPIC_SECRETS_FILE"
fi

NOW_EPOCH=$(date +%s)
CUTOFF_EPOCH=$(( NOW_EPOCH - HOURS * 3600 ))
TMP=$(mktemp /tmp/recent-sessions.XXXXXX)
trap 'rm -f "$TMP"' EXIT
export CUTOFF_EPOCH TMP

# shellcheck disable=SC1091
source "$SOURCES_DIR/_common.sh"

load_source() {
  local name="$1" enable_var="$2"
  [[ "${!enable_var}" -eq 1 ]] || return 0
  # shellcheck disable=SC1090
  source "$SOURCES_DIR/${name}.sh"
  "scan_${name}"
}

load_source claude    SOURCE_CLAUDE
load_source codex     SOURCE_CODEX
load_source gemini    SOURCE_GEMINI
load_source cursor    SOURCE_CURSOR
load_source vscode    SOURCE_VSCODE
load_source volumes   SOURCE_VOLUMES
load_source anthropic SOURCE_ANTHROPIC

if [[ ! -s "$TMP" ]]; then
  echo "No sessions in the last ${HOURS}h." >&2
  exit 0
fi

if [[ "$JSON" -eq 1 ]]; then
  sort -nr -k1,1 "$TMP" | head -n "$LIMIT" | while IFS=$'\t' read -r mtime iso source project ident hint; do
    jq -cn \
      --argjson mtime "$mtime" \
      --arg iso "$iso" --arg source "$source" \
      --arg project "$project" --arg identifier "$ident" --arg hint "$hint" \
      '{mtime:$mtime,iso:$iso,source:$source,project:$project,identifier:$identifier,hint:$hint}'
  done
else
  {
    printf 'WHEN (UTC)\tSOURCE\tPROJECT\tIDENTIFIER\tRESUME HINT\n'
    sort -nr -k1,1 "$TMP" | head -n "$LIMIT" | while IFS=$'\t' read -r mtime iso source project ident hint; do
      printf '%s\t%s\t%s\t%s\t%s\n' "$iso" "$source" "$project" "$ident" "$hint"
    done
  } | column -t -s $'\t' 2>/dev/null || sort -nr -k1,1 "$TMP" | head -n "$LIMIT"
fi
