#!/bin/bash
# setup.sh — interactive configuration for the recent-sessions skill.
#
# Walks the user through which sources to enable, then (for cloud sources)
# asks how auth should be sourced. Produces:
#   1. <skill>/config.env       — the toggle map consumed by list-recent-sessions.sh
#   2. Optionally ~/.claude/secrets/recent-sessions-anthropic.env — a 0600 env
#      file with ANTHROPIC_API_KEY, loaded on each run.
#
# The user can always edit config.env by hand; re-running setup overwrites it.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$SKILL_DIR/config.env"
SECRETS_DIR="$HOME/.claude/secrets"
DEFAULT_SECRET_FILE="$SECRETS_DIR/recent-sessions-anthropic.env"

# --- Probing ---------------------------------------------------------------

probe() {
  # $1=label $2=path — returns "yes" / "no" with row count if applicable
  local label="$1" path="$2"
  if [[ -d "$path" ]]; then
    local n
    n=$(find "$path" -maxdepth 3 -type f 2>/dev/null | head -200 | wc -l | tr -d ' ')
    echo "${label}: FOUND (~${n} files)"
  else
    echo "${label}: not found at ${path}"
  fi
}

ask() {
  # $1=prompt $2=default   → prints reply
  local prompt="$1" default="$2" reply
  if [[ -t 0 ]]; then
    # shellcheck disable=SC2162
    read -p "$prompt [$default]: " reply </dev/tty
  else
    reply=""
  fi
  echo "${reply:-$default}"
}

yesno() {
  local v
  v=$(ask "$1" "$2")
  case "$(echo "$v" | tr '[:upper:]' '[:lower:]')" in
    y|yes|1|true) echo 1 ;;
    *) echo 0 ;;
  esac
}

# --- Exploratory phase -----------------------------------------------------

cat <<'BANNER'

recent-sessions — interactive setup
───────────────────────────────────
This walks through the sources available on this machine, asks which to
enable, and wires up cloud auth if you want Anthropic sessions included.

BANNER

echo "Local probe:"
probe "  claude" "$HOME/.claude/projects"
probe "  codex  (live)" "$HOME/.codex/sessions"
probe "  codex  (archived)" "$HOME/.codex/archived_sessions"
probe "  gemini" "$HOME/.gemini/history"
probe "  cursor" "$HOME/Library/Application Support/Cursor/User/workspaceStorage"
probe "  vscode" "$HOME/Library/Application Support/Code/User/workspaceStorage"
echo "  volumes: $(ls -d /Volumes/* 2>/dev/null | tr '\n' ' ')"
echo ""

enable_claude=$(yesno    "Enable claude"    "y")
enable_codex=$(yesno     "Enable codex"     "y")
enable_gemini=$(yesno    "Enable gemini"    "y")
enable_cursor=$(yesno    "Enable cursor"    "y")
enable_vscode=$(yesno    "Enable vscode"    "y")
enable_volumes=$(yesno   "Enable volumes (scans /Volumes/* git repos — slow)" "n")
enable_anthropic=$(yesno "Enable anthropic cloud (Managed Agents sessions)"   "n")

# --- Anthropic auth wiring -------------------------------------------------

ANTHROPIC_SECRETS_FILE=""

if [[ "$enable_anthropic" -eq 1 ]]; then
  cat <<'AUTH'

Anthropic cloud needs an API key. Choose how to supply it:

  1) Doppler  — fetch once, cache to ~/.claude/secrets/recent-sessions-anthropic.env (0600).
                Matches the repo convention in CLAUDE.md ("Secrets via Doppler only").
  2) Env file — point at a path you already maintain. I won't touch it, just source it.
  3) Shell    — nothing written. You export ANTHROPIC_API_KEY yourself before running.

AUTH
  auth_choice=$(ask "Auth source (1/2/3)" "1")

  case "$auth_choice" in
    1)
      if ! command -v doppler &>/dev/null; then
        echo "doppler CLI not found in PATH — falling back to option 3 (shell env)." >&2
        ANTHROPIC_SECRETS_FILE=""
      else
        proj=$(ask "Doppler project"      "personal")
        cfg=$(ask  "Doppler config"       "dev")
        name=$(ask "Secret name"          "ANTHROPIC_API_KEY")
        mkdir -p "$SECRETS_DIR"
        val=$(doppler secrets get "$name" --project "$proj" --config "$cfg" --plain 2>/dev/null || true)
        if [[ -z "$val" ]]; then
          echo "Could not read $name from $proj/$cfg. File not written." >&2
          ANTHROPIC_SECRETS_FILE=""
        else
          umask 177
          {
            echo "# Generated by recent-sessions/setup.sh on $(date -u)"
            echo "# Cached from Doppler project=$proj config=$cfg secret=$name"
            echo "ANTHROPIC_API_KEY=${val}"
          } > "$DEFAULT_SECRET_FILE"
          ANTHROPIC_SECRETS_FILE="$DEFAULT_SECRET_FILE"
          echo "Wrote $DEFAULT_SECRET_FILE (mode 0600)."
        fi
      fi
      ;;
    2)
      custom_path=$(ask "Path to env file" "$HOME/.claude/secrets/anthropic.env")
      if [[ ! -f "$custom_path" ]]; then
        echo "Note: $custom_path does not exist yet. Create it with a line like" >&2
        echo "      ANTHROPIC_API_KEY=sk-ant-... before running the skill." >&2
      fi
      ANTHROPIC_SECRETS_FILE="$custom_path"
      ;;
    *)
      ANTHROPIC_SECRETS_FILE=""
      echo "No secret file wired up. Export ANTHROPIC_API_KEY before each run."
      ;;
  esac

  beta_header=$(ask "Anthropic beta header (leave default unless Anthropic bumps it)" "managed-agents-2025-09-25")
else
  beta_header=""
fi

# --- Write config.env ------------------------------------------------------

{
  echo "# recent-sessions config.env — generated $(date -u)"
  echo "# Hand-edit freely, or re-run:"
  echo "#   bash ~/.claude/skills/recent-sessions/scripts/setup.sh"
  echo ""
  echo "SOURCE_CLAUDE=$enable_claude"
  echo "SOURCE_CODEX=$enable_codex"
  echo "SOURCE_GEMINI=$enable_gemini"
  echo "SOURCE_CURSOR=$enable_cursor"
  echo "SOURCE_VSCODE=$enable_vscode"
  echo "SOURCE_VOLUMES=$enable_volumes"
  echo "SOURCE_ANTHROPIC=$enable_anthropic"
  echo ""
  echo "# Anthropic cloud"
  if [[ -n "$ANTHROPIC_SECRETS_FILE" ]]; then
    echo "ANTHROPIC_SECRETS_FILE=\"$ANTHROPIC_SECRETS_FILE\""
  else
    echo "# ANTHROPIC_SECRETS_FILE=  # (unset — relying on shell env at runtime)"
  fi
  if [[ -n "$beta_header" ]]; then
    echo "ANTHROPIC_BETA_HEADER=\"$beta_header\""
  fi
} > "$CONFIG_FILE"

echo ""
echo "Wrote $CONFIG_FILE:"
echo "────────────────────────────────────────────────────"
cat "$CONFIG_FILE"
echo "────────────────────────────────────────────────────"
echo ""
echo "Test it:"
echo "  bash $SCRIPT_DIR/list-recent-sessions.sh --hours 72 --limit 10"
